<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "projects"
 *
 * Auto generated by Extension Builder 2021-01-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'CBP Projects',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Beat Hausheer',
    'author_email' => 'bh@miux.ch',
    'state' => 'stable',
    'clearCacheOnLoad' => true,
    'version' => '13.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.9.99-12.4.2-13.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' => [
        'psr-4' => [
            'Miux\\Projects\\' => 'Classes',
        ],
    ],
];
