# Datei Miux/MiuxTemplate/Configuration/Services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Miux\MiuxTemplate\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'
    Miux\MiuxTemplate\Backend\EventListener\BackendPreview:
        tags:
            - name: event.listener
              identifier: 'miux_template/rendering-ctype'
              event: TYPO3\CMS\Backend\View\Event\PageContentPreviewRenderingEvent
